Repository Tecnativa/doodba-copier-template, pull requests merged in 2020-06, with the labels that each got.

#59 Disable autorebase of PRs
  .github/workflows/automerge.yml
Labels: automerge, enhancement

#61 Better explain db initialization
  docs/daily-usage.md
  docs/faq.md
Labels: automerge, documentation

#63 Fix invoke instructions
  docs/daily-usage.md
Labels: automerge, bug, documentation

#64 Fix resetdb execution outside of root folder
  tasks_downstream.py
  tests/test_tasks_downstream.py
Labels: automerge, bug

#65 Do not format on save XML files
  .vscode/settings.json.jinja
Labels: automerge, bug

#67 Answer a sensible question about pre-commit after updates
  docs/faq.md
Labels: automerge, documentation, enhancement

#68 Mount all /opt/auto in devel
  devel.yaml.jinja
  docs/daily-usage.md
  docs/faq.md
Labels: automerge, enhancement

#69 Fix invoke invocation (😁)
  .vscode/tasks.json.jinja
Labels: automerge, bug

#71 backup_deletion: set No as default answer
  copier.yml
Labels: enhancement

#72 Github Actions: don't run heavy tests on doc updates
  .github/workflows/test.yml
Labels: automerge, enhancement
