Repository Tecnativa/doodba-copier-template, pull requests merged in 2020-09, with the labels that each got.

#94 Modify multidomains structure
  .env.jinja
  .github/workflows/test.yml
  _macros.jinja
  _traefik1_labels.yml.jinja
  _traefik2_labels.yml.jinja
  common.yaml.jinja
  copier.yml
  devel.yaml.jinja
  docs/faq.md
  migrations.py
  prod.yaml.jinja
  setup-devel.yaml.jinja
  tasks.py
  tasks_downstream.py
  test.yaml.jinja
  tests/conftest.py
  tests/pytest.ini
  tests/samples/alt-domains/prod.yaml
  tests/test_migrations.py
  tests/test_nitpicking.py
  tests/test_routing.py
Labels: automerge, autorebase, enhancement

#102 Update automerge action
  .github/workflows/automerge.yml
Labels: automerge

#104 Polish bugs detected in v2.0.0a4
  _macros.jinja
  _traefik1_labels.yml.jinja
  common.yaml.jinja
  test.yaml.jinja
Labels: automerge

#105 Remove absurd labels
  _traefik1_labels.yml.jinja
  _traefik2_labels.yml.jinja
Labels: automerge with squash

#107 Format first, lint last
  .pre-commit-config.yaml.jinja
Labels: automerge

#108 Specify and test the main domain
  _macros.jinja
  common.yaml.jinja
  copier.yml
  prod.yaml.jinja
  test.yaml.jinja
  tests/test_nitpicking.py
Labels: enhancement

#110 Open all ports in devel prefixed by version
  .vscode/launch.json.jinja
  devel.yaml.jinja
  docs/daily-usage.md
Labels: automerge, enhancement

#106 New release v2.0.0
  .env.jinja
  .github/workflows/automerge.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pre-commit-config.yaml.jinja
  .vscode/launch.json.jinja
  README.md
  _macros.jinja
  _traefik1_labels.yml.jinja
  _traefik2_labels.yml.jinja
  common.yaml.jinja
  copier.yml
  devel.yaml.jinja
  docs/daily-usage.md
  docs/faq.md
  migrations.py
  poetry.lock
  prod.yaml.jinja
  pyproject.toml
  setup-devel.yaml.jinja
  tasks.py
  tasks_downstream.py
  test.yaml.jinja
  tests/conftest.py
  tests/pytest.ini
  tests/samples/alt-domains/prod.yaml
  tests/samples/cidr-whitelist/prod.yaml
  tests/samples/cidr-whitelist/test.yaml
  tests/test_default_settings.py
  tests/test_doodba_qa.py
  tests/test_migrations.py
  tests/test_nitpicking.py
  tests/test_routing.py
  tests/test_settings_effect.py
  tests/test_tasks_downstream.py
Labels: automerge, automerge without rebase, enhancement

#111 Fix incompatibility between pylint-odoo and isort
  .pre-commit-config.yaml.jinja
  tests/conftest.py
  tests/test_nitpicking.py
Labels: automerge, bug

#112 Fix isort 5 compatibility with black
  .pre-commit-config.yaml.jinja
  tests/test_nitpicking.py
Labels: automerge, bug

#114 Fix Traefik v1 port label
  _traefik1_labels.yml.jinja
Labels: automerge, bug

#117 Fix non-resilient test
  tests/test_nitpicking.py
Labels: automerge, bug

#119 Update prettier XML plugin and fix incompatibility
  .pre-commit-config.yaml.jinja
Labels: automerge, bug, enhancement

#121 Fix typo in traefik 1 entrypoints
  _traefik1_labels.yml.jinja
  tests/conftest.py
  tests/test_routing.py
Labels: automerge, bug

#120 Polish 2.1.0 release
  copier.yml
  migrations.py
  tasks.py.jinja
  tests/test_migrations.py
Labels: automerge, bug

#122 Set xmlWhitespaceSensitivity=strict for prettier
  .prettierrc.yml
  .prettierrc.yml.jinja
Labels: automerge, enhancement

#124 Ask odoo version first
  copier.yml
Labels: enhancement

#125 Add a job to autosync changes to stable into devel
  .github/workflows/sync.yml
Labels: enhancement
