Repository Tecnativa/doodba-copier-template, pull requests merged in 2020-10, with the labels that each got.

#127 Update ptvsd -> debugpy
  devel.yaml.jinja
  tasks.py.jinja
Labels: enhancement

#129 Use ghcr.io version of tecnativa/postgres-autoconf image
  common.yaml.jinja
Labels: automerge, bug

#130 Support Odoo 14.0
  .github/workflows/test.yml
  .pylintrc-mandatory.jinja
  .pylintrc.jinja
  copier.yml
  docs/faq.md
  tasks.py
  tests/samples/mqt-diffs/.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/.pylintrc.diff
  tests/samples/mqt-diffs/v10.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v10.0-.pylintrc.diff
  tests/samples/mqt-diffs/v11.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v11.0-.pylintrc.diff
  tests/samples/mqt-diffs/v12.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v12.0-.pylintrc.diff
  tests/samples/mqt-diffs/v13.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v13.0-.pylintrc.diff
  tests/samples/mqt-diffs/v14.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v14.0-.pylintrc.diff
  tests/samples/mqt-diffs/v7.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v7.0-.pylintrc.diff
  tests/samples/mqt-diffs/v8.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v8.0-.pylintrc.diff
  tests/samples/mqt-diffs/v9.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v9.0-.pylintrc.diff
  tests/test_nitpicking.py
Labels: automerge, enhancement

#132 Merge development branch
  .github/workflows/test.yml
  .pylintrc-mandatory.jinja
  .pylintrc.jinja
  copier.yml
  docs/faq.md
  tasks.py
  tests/samples/mqt-diffs/.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/.pylintrc.diff
  tests/samples/mqt-diffs/v10.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v10.0-.pylintrc.diff
  tests/samples/mqt-diffs/v11.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v11.0-.pylintrc.diff
  tests/samples/mqt-diffs/v12.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v12.0-.pylintrc.diff
  tests/samples/mqt-diffs/v13.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v13.0-.pylintrc.diff
  tests/samples/mqt-diffs/v14.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v14.0-.pylintrc.diff
  tests/samples/mqt-diffs/v7.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v7.0-.pylintrc.diff
  tests/samples/mqt-diffs/v8.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v8.0-.pylintrc.diff
  tests/samples/mqt-diffs/v9.0-.pylintrc-mandatory.diff
  tests/samples/mqt-diffs/v9.0-.pylintrc.diff
  tests/test_nitpicking.py
Labels: automerge without rebase, enhancement

#137 Support Postgres 13
  copier.yml
Labels: automerge, enhancement

#140 Increase default postgres work_mem
  common.yaml.jinja
Labels: automerge, enhancement

#142 Prepare for copier v6
  copier.yml
Labels: enhancement

#150 Only create postgres_db if not using external
  common.yaml.jinja
  devel.yaml.jinja
  prod.yaml.jinja
  test.yaml.jinja
Labels: bug

#153 Pin nodejs versions for pre-commit
  .pre-commit-config.yaml
  .pre-commit-config.yaml.jinja
Labels: automerge, enhancement

#155 Add newline between db and previous service
  common.yaml.jinja
  devel.yaml.jinja
  prod.yaml.jinja
  test.yaml.jinja
Labels: automerge, bug

#157 Add traefik 1 main domain
  _traefik1_labels.yml.jinja
Labels: automerge, bug

#158 Complete traefik 1 domain fix
  _traefik1_labels.yml.jinja
  tests/test_nitpicking.py
Labels: automerge, bug

#161 Add buttons to run start and stop tasks
  .vscode/extensions.json
  tasks.py.jinja
Labels: automerge, enhancement
