Repository Tecnativa/doodba-copier-template, pull requests merged in 2020-11, with the labels that each got.

#139 Fix debugger timeout
  .github/workflows/test.yml
  tasks.py
  tasks.py.jinja
  tests/conftest.py
  tests/test_tasks_downstream.py
Labels: bug

#163 Specify OS support
  README.md
Labels: automerge, documentation, enhancement

#165 Migrate from prettier/prettier to prettier/pre-commit
  .pre-commit-config.yaml
  .pre-commit-config.yaml.jinja
Labels: automerge with squash, bug

#160 IMP: Add Odoo tests and install task
  tasks.py.jinja
  tests/pytest.ini
  tests/test_tasks_downstream.py
Labels: enhancement

#167 Explain how to avoid the prettiermageddon when updating
  docs/faq.md
Labels: automerge, documentation

#169 Fix exception call
  tasks_downstream.py
Labels: bug

#170 Move search.followSymlinks to workspace setting
  .vscode/settings.json.jinja
  tasks_downstream.py
Labels: automerge, bug

#171 Do not color task launchers
  tasks_downstream.py
Labels: automerge, enhancement

#172 Proxy www.googleapis.com
  devel.yaml.jinja
Labels: enhancement

#175 Enhance behavior with copier 6 alphas
  copier.yml
Labels: automerge, enhancement

#176 Debugger fixes and improvements
  tasks_downstream.py
  tests/test_tasks_downstream.py
Labels: automerge, enhancement

#182 Update tests to set env variables through file instead of set-env
  .github/workflows/test.yml
Labels: automerge, bug

#184 Use GitHub packages instead of docker registry
  odoo/Dockerfile
Labels: automerge with squash

#185 Add option to skip uninstallable addons from pre-commit hooks
  .pre-commit-config.yaml.jinja
  tests/conftest.py
  tests/test_nitpicking.py
Labels: automerge with squash, enhancement
